name: Build and Deploy Jekyll Site to gh-pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle init
          echo 'gem "jekyll"' >> Gemfile
          echo 'gem "webrick"' >> Gemfile
          bundle install

      - name: Build Site
        run: bundle exec jekyll build

      - name: Deploy to gh-pages Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_site
